#! python3
list=[["Hello"],["har","sha"]]
def leng():
    le=0
    for i in range(0,len(list)):
        for j in range(0,len(list[i])):
         if(le<len(list[i][j])):
             le=len(list[i][j])
             print(le)
def prin():
    for 

if __name__ == '__main__':
    leng()
